kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  config.yml: |-
    global:
    templates:
    - '/etc/alertmanager/*.tmpl'
    route:
      receiver: alert-emailer
      group_by: ['alertname', 'priority']
      group_wait: 10s
      repeat_interval: 30m
      routes:
        - receiver: slack_prometheus
        # Send severity=slack alerts to slack.
          match:
            severity: slack
          group_wait: 10s
          repeat_interval: 1m
    receivers:
    - name: alert-emailer
      email_configs:
      - to: nwoyesamuelc@gmail.com
        send_resolved: false
        from: nwoyesamuelc@gmail.com
        smarthost: smtp.gmail.com:465
        require_tls: false
    - name: slack_prometheus
      slack_configs:
      - api_url: 'https://hooks.slack.com/services/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'      
        channel: '#myprometheus'
