apiVersion: v1
kind: Service
metadata:
  name: grafana-svc
  namespace: monitoring
spec:
  selector:
    app: grafana-server
  type: NodePort
  externalIPs:
  - 192.168.255.4
  ports:
  - name: grafana
    protocol: TCP
    port: 80
    targetPort: grafana
    nodePort: 30300